# Generated by Django 6.0.2 on 2026-03-09 17:56

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='thumbnail',
            field=models.ImageField(default='image', upload_to=products.models.product_type_thumbnail_name),
            preserve_default=False,
        ),
    ]
