# Generated by Django 6.0.2 on 2026-03-12 15:58

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='inspo_pic',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.order_inspo_pic_name),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
